apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-ako-argoapp
  name: grafana-ako-argoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-ako-argoapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-ako-argoapp
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-ako-argoapp
  name: grafana-ako-argoapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-ako-argoapp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: grafana-ako-argoapp
spec:
  ingressClassName: nginx-public
  rules:
  - host: ako-test-2.midasint.io
    http:
      paths:
      - backend:
          service:
            name: grafana-ako-argoapp
            port:
              name: grafana-ako-argoapp
        path: /
        pathType: Exact
status:
  loadBalancer: {}
