apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myfirstargoapp
  namespace: ako-argocd-workshop
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: guestbook
spec:
  project: default

  source:
    repoURL: https://github.com/aokooh/nginx-ako.git
    targetRevision: HEAD
    path: test-folder3
