apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysecondargoapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: mysecondargoapp
spec:
  project: default
  
  source:
    chart: fluent
    repoURL: https://fluent.github.io/helm-charts
    targetRevision: v1.16.2

    helm:
      releaseName: fluent-ako

  destination:
    server: https://kubernetes.default.svc
    namespace: ako-argocd-workshop

  directory:
    recurse: true
    exclude: 'config.yaml'
    include: '*.yaml'
    
