apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysecondargoapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: mysecondargoapp
spec:
  project: default
  
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
      
  destination:
    server: https://kubernetes.default.svc
    namespace: ako-argocd-workshop
    
